/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.*;
import java.util.Scanner;
import java.util.UUID;
import java.util.function.Function;

import static ticket.booking.util.UserServiceUtil.hashPassword;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;
        try{
            userBookingService=new UserBookingService();
        }
        catch(IOException e){
            System.out.println("There is something wrong");
            return;
        }
        Train trainSelectedForBooking=new Train();
        while(option!=7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = sc.nextInt();


            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp=sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp=sc.next();
                    User userToSignUp=new User(nameToSignUp,passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin=sc.next();
                    System.out.println("Enter the password to Login");
                    String passwordToLogin=sc.next();
                    User userToLogin=new User(nameToLogin,passwordToLogin,hashPassword(passwordToLogin),new ArrayList<>(),"");
                    try{
                        userBookingService=new UserBookingService(userToLogin);
                    } catch (IOException e) {
                        System.out.println("Error loading  user data");
                        break;
                    }
                    if(userBookingService.userLogin()){
                        System.out.println("Login Successful");
                    }
                    else{
                        System.out.println("Invalid Username or password");
                    }
                    break;
                case 3:
                    if(userBookingService.getUser()==null){
                        System.out.println("PLease login First");
                        break;
                    }
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Enter the source station");
                    String source=sc.next();
                    System.out.println("Enter the destination station");
                    String dest=sc.next();
                    List<Train> trains=userBookingService.getTrains(source,dest);
                    int index=1;
                    for(Train t:trains){
                        System.out.println(index+"TrainId: "+t.getTrainId());
                        index++;
                        t.getStationTimes().forEach((station,time)->
                                System.out.println("Station"+station+"Time"+time)
                        );
                    }
                    System.out.println("Select a train by typing 1,2,3....");
                    trainSelectedForBooking=trains.get(sc.nextInt()-1);
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats=userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> row:seats){
                        for(Integer val:row){
                            System.out.println(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row=sc.nextInt();
                    System.out.println("Enter the column");
                    int col=sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked=userBookingService.bookTrainSeats(row,col,trainSelectedForBooking);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked, Enjoy your Journey");

                    }
                    else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                case 6:
                    if(userBookingService.getUser()==null){
                        System.out.println("Please login first");
                        break;
                    }
                    System.out.println("Enter the ticket ID to cancel");
                    String ticketIdToCancel=sc.next();
                    System.out.println(userBookingService.cancelBooking(ticketIdToCancel) ? "Booking Cancelled" :"Could not Cancel" );
                    break;
                default:
                    break;



            }
        }
    }
}
